import './style/index.less';

export { CEchart } from './components';
export { getChartMeta, listChartMetas } from './metas';
export { buildOption } from './utils/buildOption';
export { CONFIG_VERSION, createDefaultConfig, normalizeConfig } from './utils/config';
export { getDefaultTheme, registerTheme, setDefaultTheme } from './utils/theme';
export type { ChartMeta } from './metas';
export type {
  BarChartConfig,
  BarChartData,
  BarChartSeries,
  BarChartSettings,
  BarLabelSetting,
  BarTooltipSetting,
  CartesianChartSeries,
  CartesianTooltipSetting,
  CEchartProps,
  ChartConfig,
  ChartConfigMap,
  ChartData,
  ChartDataItem,
  ChartSettings,
  ChartTheme,
  ChartType,
  ComboChartConfig,
  ComboChartData,
  ComboChartSeries,
  ComboChartSettings,
  ComboSeriesSetting,
  LabelSetting,
  LegendSetting,
  LineChartConfig,
  LineChartData,
  LineChartSeries,
  LineChartSettings,
  LineLabelSetting,
  LineSeriesSetting,
  PieChartConfig,
  PieChartData,
  PieChartSettings,
  PieLabelSetting,
  PieTooltipSetting,
  ScatterChartConfig,
  ScatterChartData,
  ScatterChartSeries,
  ScatterChartSettings,
  ScatterSeriesSetting,
  SeriesSetting,
  SeriesStyleSetting,
  SettingChangeEvent,
  SettingFieldKey,
  SettingItemKey,
  TitleSetting,
  ToolContext,
  ToolItem,
  TooltipSetting,
  XAxisSetting,
  YAxisSetting,
} from './types';
export { CEchart as default } from './components';
